# Docker安装全模块

version: '3'
services:
  # MCP 接入点服务
  voiceprint-api:
    build: .
    image: voiceprint-api:local
    container_name: voiceprint-api
    restart: always
    networks:
      - xiaozhi-local
    ports:
      - "8005:8005"
    security_opt:
      - seccomp:unconfined
    environment:
      - TZ=Asia/Shanghai
    volumes:
      # 配置文件目录
      - ./data:/app/data
networks:
  xiaozhi-local:
    external: true
